kotlin.code.style=official
kotlin.mpp.stability.nowarn=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
GROUP=com.surrealdb
VERSION_NAME=0.2.0-SNAPSHOT
POM_URL=https://github.com/surrealdb/surrealdb.kotlin
POM_SCM_URL=https://github.com/surrealdb/surrealdb.kotlin
POM_SCM_CONNECTION=scm:git:git://github.com/surrealdb/surrealdb.kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/surrealdb/surrealdb.kotlin.git
POM_LICENSE_NAME=Apache-2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=surrealdb
POM_DEVELOPER_NAME=SurrealDB
